import styles from './privacy.module.css'

export default function PrivacyPolicy() {
	return (
		<div className={styles.container}>
			<h1 className={styles.title}>PRIVACY POLICY</h1>
			<p className={styles.date}>Effective date: Jan 14, 2025</p>

			<section className={styles.section}>
				<h2>Overview</h2>
				<p>
					Welcome to Soulmate AI. We are committed to protecting and respecting
					your privacy.
				</p>
				<p>
					This Policy explains our practices regarding the collection, use,
					disclosure, and protection of information that is collected through
					our Service, as well as your choices regarding the collection and use
					of information.
				</p>
				<p>
					Our Privacy policy applies to all users, and others who access the App
					(&quot;Users&quot;).
				</p>
				<p>
					Please read the following privacy policy, for information regarding
					the ways your personal information may be processed, carefully. When
					you use the app you acknowledge that you have read, understood, and
					agree to be bound by these terms.
				</p>
			</section>

			<section className={styles.section}>
				<h2>I. What kind of information do we collect</h2>
				<h3>Information and content you provide:</h3>
				<ul>
					<li>
						Collect data, including information that directly or indirectly
						identifies you. When you use our device, we automatically collect
						certain information from your device. Include data about your
						device, device ID, and other technical information.
					</li>
					<li>
						Authorization and/or Account Information. When you sign up for an
						account, we require certain information such as your user ID, email
						address or other login information - depending on the App settings.
					</li>
					<li>
						Content Information, i.e. photos, pictures, video and audio files,
						documents and other data that you upload using the App.
					</li>
				</ul>

				<h3>Information automatically collected</h3>
				<p>
					Some information – such as IP address and/or browser and device
					characteristics – is collected automatically when you visit our Apps.
				</p>
				<p>
					We automatically collect certain information when you visit, use or
					navigate the Apps. This information does not reveal your specific
					identity (like your name or contact information) but may include
					device and usage information, such as your IP address, including your
					browser and device characteristics, operating system, language
					preferences, referring URLs, device name, country, location,
					information about how and when you use our Apps and other technical
					information. This information is primarily needed to maintain the
					security and operation of our Apps, and for our internal analytics and
					reporting purposes.
				</p>
				<p>
					To improve the performance and reliability of our apps, and to help
					with troubleshooting in case of issues while you use the apps, we
					collect performance data and crash analytics.
				</p>

				<h3>Analytics information:</h3>
				<p>
					Information we collect automatically through the use of technology.
					When you visit our website, use our mobile app, read our emails or
					otherwise engage with us, we and our business partners may
					automatically collect certain information about your computer or
					device through a variety of tracking technologies, including cookies,
					web beacons, log files, embedded scripts, location-identifying
					technologies, or other tracking/recording tools (collectively,
					&quot;tracking technologies&quot;), and we may combine this
					information with other personal information we collect about you. We
					use these tracking technologies to collect usage and device
					information.
				</p>
				<p>
					We use third-party automatic data processing technologies (such as
					Google and Facebook) to analyze certain information sent by your
					device or our App. Automatic data processing technologies (advertising
					or analytics tools) provide us with the data described below. We do
					not control, supervise or respond for how the third parties process
					your personal data, that might be processed by their own means (not
					through our App). Any information request regarding the disclosure of
					your personal information to us should be directed to such third
					parties.
				</p>

				<h3>Device information:</h3>
				<p>
					We collect information from and about your phone devices you use that
					integrate with our Services, as well as the information generated by
					these devices, depending on the permissions you have granted. Here are
					some examples of the device information we collect:
				</p>
				<ul>
					<li>
						type of your mobile device and operational system version which is
						installed on your mobile device;
					</li>
					<li>region information of your mobile device;</li>
					<li>region associated with your SIM card;</li>
					<li>Internet Protocol (&quot;IP&quot;) address;</li>
					<li>
						Identity For Advertisers / Advertising ID which is a string of
						numbers and letters that identifies your individual smartphone or
						tablet.
					</li>
				</ul>
			</section>

			<section className={styles.section}>
				<h2>II. How do we use this information?</h2>
				<p>
					In addition to some of the specific uses of the information we
					describe in this Privacy Policy, we may use the information received
					to:
				</p>
				<ul>
					<li>
						To make our service available. We use information that you submit
						and information that is processed automatically to provide you with
						all requested services.
					</li>
					<li>
						To improve, test and monitor the effectiveness of our App. We use
						information that is processed automatically to better understand
						user behavior and trends, detect potential outages and technical
						issues, to operate, protect, improve, and optimize our App.
					</li>
					<li>
						To communicate with you. We use the information we have to
						communicate with you through newsletters, i.e. to send you marketing
						notifications, receive your feedback about our App experience, and
						let you know about our policies and terms. We also use your
						information to respond to you when you contact us.
					</li>
					<li>
						To use the information we receive to help you effectively access
						your information after logging in, remember the information so that
						you do not have to re-enter it after you log in when you visit or
						the next time you visit the service.
					</li>
				</ul>
				<p>
					If any new purposes for processing your personal data arise we will
					let you know we start to process information on that other purpose by
					introducing the corresponding changes to this Privacy policy.
				</p>
			</section>

			<section className={styles.section}>
				<h2>III. How do we share your information?</h2>
				<p>
					Soulmate AI only share personally identifiable information with third
					parties when that sharing is permitted by you, or when it&apos;s
					necessary to complete an action in the software or service, or when
					legally required to do so. Here are some situations where this can
					occur:
				</p>

				<h3>To help improve or promote our services:</h3>
				<p>
					We may share information and aggregate data we collect on usage and
					user behavior with third parties, to help improve or promote Soulmate
					AI, but we do it in such a way that no individual user can be
					identified or linked to any specific action or information.
				</p>
				<p>
					We generally retain your personal information for as long as is
					necessary for performing the functional service of the App and to
					comply with our legal obligations. If you no longer want us to use
					your information that we physically access and store, you can request
					that we erase your personal information and close your account.
				</p>
				<p>
					However, some data may still be stored for a certain time period (but
					no longer than the storage purpose requires) if information is
					necessary to comply with legal obligation (taxation, accounting,
					audit) or in order to maintain safety and data backup settings,
					prevent fraud or other malicious acts.
				</p>
			</section>

			<section className={styles.section}>
				<h2>IV. Security</h2>
				<p>
					We use various security technologies and procedures to prevent the
					loss, misuse, unauthorized access or disclosure of information. Please
					note that no data security measures can always guarantee 100%
					security. Our system and the communication network you access to our
					services may have security breaches and failures due to circumstances
					beyond our reasonable control.
				</p>
				<p>
					The security of your personal information is highly important. We will
					try our best to make sure the data is protected from any fraud. For
					this reason, we have a secure environment to collect, store and track
					the information using latest technologies.
				</p>
			</section>

			<section className={styles.section}>
				<h2>V. User-Generated Content and Copyright</h2>
				<p>
					When you create custom chat roles or dialogues within the application,
					you retain copyright over your original contributions. By using this
					feature, you grant us a non-exclusive, worldwide, royalty-free license
					to use, reproduce, and display your contributions solely for the
					purposes of providing and improving the application&apos;s services.
				</p>
				<p>
					We respect your intellectual property and will not claim ownership of
					the original roles or dialogues you create. However, modifications or
					derivatives created by the AI system based on user inputs may remain
					under our control to ensure compliance with operational guidelines.
				</p>
			</section>

			<section className={styles.section}>
				<h2>VI. Protection of Minors</h2>
				<p>
					Our application is not intended for use by individuals under the age
					of 18. If we become aware that we have collected personal information
					from a child under 18 without parental consent, we will take immediate
					steps to delete such information.
				</p>
				<p>
					Parents or guardians are encouraged to monitor their children&apos;s
					use of the application and to educate them on online safety and
					responsible behavior.
				</p>
			</section>

			<section className={styles.section}>
				<h2>VII. Changes</h2>
				<p>
					We will not notify you in advance if there is any change to our
					privacy policy so you are obliged to check the changes section of the
					privacy policy regularly.
				</p>
			</section>

			<section className={styles.section}>
				<h2>VIII. Your consent</h2>
				<p>By using our site, you consent to our web site privacy policy.</p>
			</section>

			<section className={styles.section}>
				<h2>IX. How to contact us?</h2>
				<p>
					If you have any questions about our Privacy policy, please feel free
					to contact us:{' '}
					<a href='mailto:alexander.strom@icloud.com'>
						alexander.strom@icloud.com
					</a>
				</p>
			</section>
		</div>
	)
}
